const express = require('express');
require('dotenv').config();
const cookieParser = require('cookie-parser'); // Adding middleware for parsing cookies
const eventsRouter = require('./routers/event.router');
const authRouter = require('./routers/auth.router'); // Importing the authentication route
const userRouter = require('./routers/user.router'); // Importing the user route
const swaggerUi = require('swagger-ui-express'); // Importing Swagger UI
const swaggerJsdoc = require('swagger-jsdoc'); // Importing Swagger JSDoc

const app = express();

// Middleware to parse cookies
app.use(cookieParser());

// Middleware to parse JSON requests
app.use(express.json());

app.get('/', (req, res) => {
    res.send('Welcome to my PlayTogether API!');
});

// Swagger configuration
const options = {
    definition: {
        openapi: '3.0.0', // OpenAPI version
        info: {
            title: 'PlayTogether API', // Name of your API
            version: '1.0.0', // API version
            description: 'API for PlayTogether with documentation generated by Swagger', // Description of the API
        },
    },
    apis: ['./routers/*.js', './controllers/*.js'],
};

const swaggerSpec = swaggerJsdoc(options);

// Route to serve the Swagger documentation
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));

// Routes
app.use('/api/events', eventsRouter); // Events-related routes
app.use('/api/auth', authRouter); // Authentication-related routes
app.use('/api/users', userRouter); // User-related routes

// Global error handling for uncaught exceptions
process.on('uncaughtException', (err) => {
    console.error('An error occurred:', err);
});

// Global error handling for unhandled promise rejections
process.on('unhandledRejection', (reason) => {
    console.error('A promise was rejected without a handler:', reason);
});

// Starting the server
app.listen(4000, () => {
    console.log('Server running at http://localhost:4000');
});
